local particle_animations = {}

particle_animations.get_gleba_water_cane_particle_pictures = function(options)
  local options = options or {}
  return
  {
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-01.png",
      line_length = 4,
      width = 17,
      height = 16,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-02.png",
      line_length = 4,
      width = 4,
      height = 9,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-03.png",
      line_length = 4,
      width = 10,
      height = 14,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-04.png",
      line_length = 4,
      width = 8,
      height = 11,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-05.png",
      line_length = 4,
      width = 14,
      height = 13,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-06.png",
      line_length = 4,
      width = 14,
      height = 12,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-07.png",
      line_length = 4,
      width = 11,
      height = 10,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-08.png",
      line_length = 4,
      width = 17,
      height = 14,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-09.png",
      line_length = 4,
      width = 14,
      height = 16,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-10.png",
      line_length = 4,
      width = 11,
      height = 20,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-11.png",
      line_length = 4,
      width = 21,
      height = 18,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    -- {
    --   filename = "__base__/graphics/particle/wooden-particle/wooden-particle-12.png",
    --   line_length = 4,
    --   width = 14,
    --   height = 32,
    --   frame_count = 16,
    --   animation_speed = options.animation_speed or 0.5,
    --   scale = 0.5 * (options.scale or 1),
    --   tint = options.tint,
    --   tint_as_overlay = options.tint_as_overlay,
    -- },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-13.png",
      line_length = 4,
      width = 14,
      height = 18,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-14.png",
      line_length = 4,
      width = 12,
      height = 24,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-15.png",
      line_length = 4,
      width = 14,
      height = 19,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-16.png",
      line_length = 4,
      width = 24,
      height = 12,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    -- {
    --   filename = "__base__/graphics/particle/wooden-particle/wooden-particle-17.png",
    --   line_length = 4,
    --   width = 25,
    --   height = 15,
    --   frame_count = 16,
    --   animation_speed = options.animation_speed or 0.5,
    --   scale = 0.5 * (options.scale or 1),
    --   tint = options.tint,
    --   tint_as_overlay = options.tint_as_overlay,
    -- },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-18.png",
      line_length = 4,
      width = 22,
      height = 23,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-19.png",
      line_length = 4,
      width = 32,
      height = 29,
      frame_count = 16,
      animation_speed = 0.5,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    -- {
    --   filename = "__base__/graphics/particle/wooden-particle/wooden-particle-20.png",
    --   line_length = 4,
    --   width = 17,
    --   height = 29,
    --   frame_count = 16,
    --   animation_speed = options.animation_speed or 0.5,
    --   scale = 0.5 * (options.scale or 1),
    --   tint = options.tint,
    --   tint_as_overlay = options.tint_as_overlay,
    -- },
    -- {
    --   filename = "__base__/graphics/particle/wooden-particle/wooden-particle-21.png",
    --   line_length = 4,
    --   width = 15,
    --   height = 32,
    --   frame_count = 16,
    --   animation_speed = options.animation_speed or 0.5,
    --   scale = 0.5 * (options.scale or 1),
    --   tint = options.tint,
    --   tint_as_overlay = options.tint_as_overlay,
    -- },
    -- {
    --   filename = "__base__/graphics/particle/wooden-particle/wooden-particle-22.png",
    --   line_length = 4,
    --   width = 34,
    --   height = 19,
    --   frame_count = 16,
    --   animation_speed = options.animation_speed or 0.5,
    --   scale = 0.5 * (options.scale or 1),
    --   tint = options.tint,
    --   tint_as_overlay = options.tint_as_overlay,
    -- },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-23.png",
      line_length = 4,
      width = 34,
      height = 43,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-24.png",
      line_length = 4,
      width = 38,
      height = 33,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    },
    {
      filename = "__base__/graphics/particle/wooden-particle/wooden-particle-25.png",
      line_length = 4,
      width = 45,
      height = 50,
      frame_count = 16,
      animation_speed = options.animation_speed or 0.5,
      scale = 0.5 * (options.scale or 1),
      tint = options.tint,
      tint_as_overlay = options.tint_as_overlay,
    }
  }

end

return particle_animations
